Add Shout feature
therealshabi/AQLite pull request #1
Opened 2018-11-09 15:59 UTC by rajatgoyal715

2018-12-16 09:26 UTC, therealshabi commented
Can you please write a Javadoc for the classes, methods and variables used, so that the functions becomes self-explanatory. Also, rebase your branch to the dev branch, I want to first merge it to the dev branch, test it and then maybe merge to master after that.

2018-12-16 13:33 UTC, therealshabi requested changes
Can you please write a Javadoc for the classes, methods and variables used, so that the functions becomes self-explanatory. Also, rebase your branch to the dev branch, I want to first merge it to the dev branch, test it and then maybe merge to master after that.

2018-12-17 10:35 UTC, rajatgoyal715 commented
@therealshabi Please review the changes once again and tell me if anything else is needed.

2018-12-17 10:39 UTC, therealshabi commented on aqlite/src/main/java/technolifestyle/com/aqlite/AQLite.kt
> +
Javadoc missing

2018-12-17 10:40 UTC, therealshabi commented on aqlite/src/main/java/technolifestyle/com/aqlite/AQLite.kt
> +
Add for both the method and the enum

2018-12-17 10:47 UTC, merged